# Generated by Django 5.1.5 on 2025-01-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table='cars',
        ),
    ]
