# Generated by Django 5.1.5 on 2025-01-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_alter_cars_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='available',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='chases_id',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='drive_type',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='engine_power',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='first_registration',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='interior_material',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='millage',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='transmission',
        ),
    ]
