# Generated by Django 5.1.5 on 2025-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_remove_cars_available_remove_cars_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='media/car_images/'),
        ),
        migrations.AlterField(
            model_name='carthumbnail',
            name='image',
            field=models.ImageField(max_length=500, upload_to='car_thumbnail'),
        ),
    ]
