# Generated by Django 5.1.2 on 2024-10-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_stff',
            new_name='is_staff',
        ),
    ]
