# Generated by Django 5.1.2 on 2024-10-30 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0002_rename_is_stff_users_is_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
