# Generated by Django 5.1.2 on 2024-10-30 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0003_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=5)),
                ('transmission', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('avalability', models.CharField(max_length=5)),
                ('model', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['publish_date'],
            },
        ),
        migrations.CreateModel(
            name='CarsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_image')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='adminn.cars')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
