# Generated by Django 5.1.2 on 2024-10-31 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0004_cars_carsimages_profilepicure'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carsimages',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='adminn.cars'),
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
        migrations.DeleteModel(
            name='ProfilePicure',
        ),
    ]
