# Generated by Django 5.1.2 on 2024-10-31 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0005_cars_user_alter_carsimages_car_alter_users_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table='cars',
        ),
        migrations.AlterModelTable(
            name='carsimages',
            table='car_image',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.CreateModel(
            name='ProfilePicure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_picture',
            },
        ),
    ]
