# Generated by Django 5.1.2 on 2024-10-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0006_alter_cars_table_alter_carsimages_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(default='', upload_to='cars_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CarsImages',
        ),
    ]
