# Generated by Django 5.1.2 on 2024-10-31 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0007_cars_image_alter_users_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepicure',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
