# Generated by Django 5.1.2 on 2024-10-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0009_carimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carimage',
            table='car_image',
        ),
    ]
