# Generated by Django 5.1.2 on 2024-11-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0010_alter_carimage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='image',
        ),
    ]
