# Generated by Django 5.1.2 on 2024-11-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0011_remove_cars_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='user',
        ),
    ]
