# Generated by Django 5.1.2 on 2024-11-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0012_remove_cars_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='avalability',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='model',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='price',
        ),
    ]
