# Generated by Django 5.1.2 on 2024-11-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0014_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
