# Generated by Django 5.1.2 on 2024-11-05 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0015_delete_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePicure',
            new_name='ProfilePicture',
        ),
    ]
