# Generated by Django 5.1.2 on 2024-11-09 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0016_rename_profilepicure_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=5)),
                ('transmission', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('avalable', models.BooleanField(default=True)),
                ('model', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Car',
                'ordering': ['publish_date'],
            },
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adminn.car'),
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
