# Generated by Django 5.1.2 on 2024-11-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0017_car_alter_carimage_car_delete_cars'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='Cars',
        ),
    ]
