# Generated by Django 5.1.2 on 2024-11-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0018_alter_car_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='Car',
        ),
    ]
