# Generated by Django 5.1.2 on 2024-11-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0019_alter_car_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='Cars',
        ),
    ]
