# Generated by Django 5.1.2 on 2024-11-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0020_alter_car_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-publish_date']},
        ),
    ]
