# Generated by Django 5.1.2 on 2024-11-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0021_alter_car_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='avalable',
            new_name='available',
        ),
    ]
