# Generated by Django 5.1.2 on 2024-11-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0022_rename_avalable_car_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['publish_date']},
        ),
    ]
