# Generated by Django 5.1.2 on 2024-11-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0023_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterField(
            model_name='car',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
