# Generated by Django 5.1.2 on 2024-11-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0024_alter_car_options_alter_car_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='available',
        ),
    ]
