# Generated by Django 5.1.2 on 2024-11-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0025_remove_car_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
