# Generated by Django 5.1.2 on 2024-11-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0026_car_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
