# Generated by Django 5.1.2 on 2024-11-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0027_alter_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
