# Generated by Django 5.1.2 on 2024-11-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0028_alter_car_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
