# Generated by Django 5.1.2 on 2024-11-10 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0029_alter_car_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Carthumbbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_thumbnail')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='adminn.car')),
            ],
        ),
    ]
