# Generated by Django 5.1.2 on 2024-11-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0030_alter_users_is_active_carthumbbnail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carthumbbnail',
            new_name='CarThumbnail',
        ),
        migrations.AlterModelTable(
            name='carthumbnail',
            table='car_thumbnail',
        ),
    ]
