# Generated by Django 5.1.2 on 2024-11-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0031_rename_carthumbbnail_carthumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='car_model',
        ),
    ]
