# Generated by Django 5.1.2 on 2024-11-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0032_rename_model_car_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carthumbnail',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='adminn.car'),
        ),
    ]
