# Generated by Django 5.1.2 on 2024-11-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0033_alter_carthumbnail_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cars',
        ),
    ]
