# Generated by Django 5.1.2 on 2024-11-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminn', '0034_rename_car_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='available',
            field=models.CharField(default='Yes', max_length=3),
        ),
    ]
